version: '3.9'

services:
  back:
    container_name: backend
    build: ./shrop-back
    ports:
      - "3000:3000"
    networks:
      default:
        aliases:
          - back
  
  front:
    container_name: frontend
    build: ./shrop
    ports:
      - "8080:8080"
    